### ISSUE TITLE
Is there a plan to support Alpine image?

### ISSUE THREAD

**Issue by JermineHu** [ceph/ceph-container#846] opened 2017-11-20 09:33 UTC
Alpine image will be controls the size of the final image effectively！👍 Just a suggestion！

**Comment by leseb** [comment] 2017-12-15 13:34
This is support for Kraken but no one has done anything for Luminous or above yet.
I guess it's a nice plan but not on the top of the list now.
Also pushing something in Alpine doesn't sound that straightforward...

What's the big thing around Alpine anyway? The size? The "standard"?
Thanks!

**Comment by slang800** [comment] 2018-03-29 18:37
This issue is basically a duplicate of #132

**Closed** 2020-04-09 00:42 UTC
Labels: wontfix
