### ISSUE TITLE
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

### ISSUE THREAD

**Issue by fantastic2085** [ceph/ceph-container#2126] opened 2023-06-16 07:54 UTC
Is this a bug report or feature request?
* Bug Report

**Bug Report**
![image](https://github.com/ceph/ceph-container/assets/4116773/8b17d4ce-00e2-478e-903c-8cd531e77f3d)

What happened:
Executed command： 
**make FLAVORS=pacific-16.2.7,centos,8 BASEOS_REGISTRY=quay.io/centos BASEOS_REPO=centos BASEOS_TAG=8 build**

What you expected to happen:

How to reproduce it (minimal and precise):

**Environment**:
* OS (e.g. from /etc/os-release):
![image](https://github.com/ceph/ceph-container/assets/4116773/b7f968ac-0f4a-48fb-a058-c0c6e6586757)

* Kernel (e.g. `uname -a`):
5.14.0-325.el9.x86_64
* Docker version (e.g. `docker version`):
![image](https://github.com/ceph/ceph-container/assets/4116773/71fe85be-1966-40c0-a397-be6d0a91ed7c)

* Ceph version (e.g. `ceph -v`):

**Comment by saranyareddy24** [comment] 2023-06-21 10:40
You can use centos stream8 image 
Duplicate of issue: https://github.com/ceph/ceph-container/issues/2113

**Comment by fantastic2085** [comment] 2023-06-27 03:58
Thank you for your answer @saranyareddy24

**Comment by fantastic2085** [comment] 2023-06-27 03:59
May I ask you about #2127 @saranyareddy24

**Comment by saranyareddy24** [comment] 2023-06-27 04:22
yes

**Closed** 2024-04-18 20:02 UTC
Labels: wontfix
