### ISSUE TITLE
Can't activate osd after upgrade from jewel to Luminous 

### ISSUE THREAD

**Issue by jianyunet** [ceph/ceph-container#893] opened 2018-02-04 15:51 UTC
Host: ubuntu 16.04
Docker: 1.13.1

Previously installed ceph/daemon, jewel with 3 osds and works fine.

After pull latest tag-stable-3.0-luminous-ubuntu-16.04, mon / mgr is working correctly and everything looks good, only osd images can't be migrated, the previous jewel image can be used to recover running status.

Error log:

```
root@jianyu-server:/home/jianyu# docker logs osd0
2018-02-04 13:31:32  /entrypoint.sh: static: does not generate config
main_activate: path = /dev/disk/by-id/ata-WDC_WD40-SN-part1
get_dm_uuid: get_dm_uuid /dev/disk/by-id/ata-WDC_WD40-SN-part1 uuid path is /sys/dev/block/8:17/dm/uuid
command: Running command: /sbin/blkid -o udev -p /dev/disk/by-id/ata-WDC_WD40-SN-part1
command: Running command: /sbin/blkid -p -s TYPE -o value -- /dev/disk/by-id/ata-WDC_WD40-SN-part1
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_mount_options_xfs
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup osd_fs_mount_options_xfs
mount: Mounting /dev/disk/by-id/ata-WDC_WD40-SN-part1 on /var/lib/ceph/tmp/mnt.RCaleR with options noatime,inode64
command_check_call: Running command: /bin/mount -t xfs -o noatime,inode64 -- /dev/disk/by-id/ata-WDC_WD40-SN-part1 /var/lib/ceph/tmp/mnt.RCaleR
activate: Cluster uuid is 263f8595-bedb-40d9-add9-532094dc1720
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
activate: Cluster name is ceph
activate: OSD uuid is 21591da2-b7cd-461f-80be-470dfbeb23a9
activate: OSD id is 0
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup init
command: Running command: /usr/bin/ceph-detect-init --default sysvinit
activate: Marking with init system none
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/tmp/mnt.RCaleR/none
activate: ceph osd.0 data dir is ready at /var/lib/ceph/tmp/mnt.RCaleR
move_mount: Moving mount to final location...
command_check_call: Running command: /bin/mount -o noatime,inode64 -- /dev/disk/by-id/ata-WDC_WD40-SN-part1 /var/lib/ceph/osd/ceph-0
command_check_call: Running command: /bin/umount -l -- /var/lib/ceph/tmp/mnt.RCaleR
2018-02-04 13:31:34  /entrypoint.sh: SUCCESS
usage: ceph-osd -i <ID> [flags]
  --osd-data PATH data directory
  --osd-journal PATH
                    journal file or block device
  --mkfs            create a [new] data directory
  --mkkey           generate a new secret key. This is normally used in combination with --mkfs
  --convert-filestore
                    run any pending upgrade operations
  --flush-journal   flush all data out of journal
  --mkjournal       initialize a new journal
  --check-wants-journal
                    check whether a journal is desired
  --check-allows-journal
                    check whether a journal is allowed
2018-02-04 13:31:34.824048 7f713832fe00 -1 must specify '-i #' where # is the osd number
  --check-needs-journal
                    check whether a journal is required
  --debug_osd <N>   set debug level (e.g. 10)
  --get-device-fsid PATH
                    get OSD fsid for the given block device

  --conf/-c FILE    read configuration from the given configuration file
  --id/-i ID        set ID portion of my name
  --name/-n TYPE.ID set name
  --cluster NAME    set cluster name (default: ceph)
  --setuser USER    set uid to user or uid (and gid to user's gid)
  --setgroup GROUP  set gid to group or gid
  --version         show version and quit

  -d                run in foreground, log to stderr.
  -f                run in foreground, log to usual location.
  --debug_ms N      set message debug level (e.g. 1)

```

I saw there is a recent fix for disk list to use /dev/disk/by-id/...  instead of mapper, and this path is still used in osd_disk_activate.sh, might be an issue?

```
MOUNTED_PART="/dev/mapper/${DATA_UUID}"
```

**Comment by leseb** [comment] 2018-02-08 10:15
Let me update ttag-stable-3.0-luminous-ubuntu-16.04

**Comment by leseb** [comment] 2018-02-08 11:16
stable images are building here: https://hub.docker.com/r/ceph/daemon/builds/
They will able available soon.

I'm closing this. Thanks

**Closed by leseb** 2018-02-08 11:16 UTC

**Comment by foreverhex** [comment] 2018-02-10 15:22
Hi @leseb ,

I found new information and found a fix. It's caused by /proc/mounts is not pointing to my specified device id, as I preferred to use below human-friendly path:

```
/dev/disk/by-id/ata-WDC_WD40-......-part1
```

It worked well one year before, but somehow failed in recent version, as the osd_disk_activate.sh has to follow the /dev/sdx path.

The fix is simple, probably you can help to review and make a change, I have tested in my server.

Thanks.

```
    actual_part=$(readlink -f "${MOUNTED_PART}")
    OSD_ID=$(grep "${actual_part}" /proc/mounts | awk '{print $2}' | sed -r 's/^.*-([0-9]+)$/\1/')
```
