### ISSUE TITLE
Unable to write to '/var/log/ceph/ceph.log' for channel 'cluster'

### ISSUE THREAD

**Issue by xs233** [ceph/ceph-container#1107] opened 2018-07-02 02:20 UTC
I start mon like this:
```
docker run -d --net=host \
--name mon \
--privileged=true \
-v /etc/ceph:/etc/ceph \
-v /var/lib/ceph/:/var/lib/ceph/ \
-v /var/log/ceph/:/var/log/ceph/ \
-e MON_IP=10.1.135.180 \
-e CEPH_PUBLIC_NETWORK=10.1.135.0/24 \
ceph/daemon mon
```
I want to specify the log location, but it failed! Check the container log
```
2018-07-02 02:06:05.487856 7fcb6abb4700  0 mon.node1@0(leader).osd e1 crush map has features 288514050185494528, adjusting msgr requires
2018-07-02 02:06:05.487873 7fcb6abb4700  0 mon.node1@0(leader).osd e1 crush map has features 288514050185494528, adjusting msgr requires
2018-07-02 02:06:05.487885 7fcb6abb4700  0 mon.node1@0(leader).osd e1 crush map has features 1009089990564790272, adjusting msgr requires
2018-07-02 02:06:05.487938 7fcb6abb4700  0 mon.node1@0(leader).osd e1 crush map has features 288514050185494528, adjusting msgr requires
2018-07-02 02:06:05.488108 7fcb6abb4700  1 mon.node1@0(leader).log v1 unable to write to '/var/log/ceph/ceph.log' for channel 'cluster': (13) Permission denied
2018-07-02 02:06:05.488199 7fcb6abb4700  1 mon.node1@0(leader).paxosservice(auth 1..1) refresh upgraded, format 0 -> 2
2018-07-02 02:06:05.490520 7fcb6abb4700  0 log_channel(cluster) log [DBG] : fsmap 
2018-07-02 02:06:05.490668 7fcb6abb4700  1 mon.node1@0(leader).pg v1 check_osd_map will clear pg_map data
2018-07-02 02:06:05.490677 7fcb6abb4700  1 mon.node1@0(leader).pg v1 encode_pending clearing pgmap data at v2
2018-07-02 02:06:05.491258 7fcb6abb4700  0 log_channel(cluster) log [DBG] : osdmap e1: 0 total, 0 up, 0 in
2018-07-02 02:06:05.491593 7fcb6abb4700  0 log_channel(cluster) log [DBG] : mgrmap e1: no daemons active
2018-07-02 02:06:05.493915 7fcb6abb4700  1 mon.node1@0(leader).log v2 unable to write to '/var/log/ceph/ceph.log' for channel 'cluster': (13) Permission denied
2018-07-02 02:06:06.495794 7fcb6abb4700  1 mon.node1@0(leader).log v3 unable to write to '/var/log/ceph/ceph.log' for channel 'cluster': (13) Permission denied
```

**Comment by Raboo** [comment] 2018-07-04 12:15
duplicate of #1094

There is a work-around in my latest comment.

**Closed** 2019-10-15 11:33 UTC
