### ISSUE TITLE
Hanging when run ceph/daemon demo

### ISSUE THREAD

**Issue by hrchu** [ceph/ceph-container#815] opened 2017-10-16 07:36 UTC
Version and mode: ceph/daemon:tag-stable-3.0-luminous-ubuntu-16.04 demo

Command: ```docker run -it --net=host -v /etc/ceph/:/etc/ceph/ -e CEPH_NETWORK=10.0.2.0/24 -e MON_IP=10.0.2.15 -e CEPH_PUBLIC_NETWORK=10.0.2.0/24 -e CEPH_DEMO_UID=qqq -e CEPH_DEMO_ACCESS_KEY=qqq -e CEPH_DEMO_SECRET_KEY=qqq --name rgw12 ceph/daemon:tag-stable-3.0-luminous-ubuntu-16.04 demo```

Hang in  ```/entrypoint.sh: Setting up a demo user...```

Full stdout info
```
root@VirtualBox# docker run -it --net=host -v /etc/ceph/:/etc/ceph/ -e CEPH_NETWORK=10.0.2.0/24 -e MON_IP=10.0.2.15 -e CEPH_PUBLIC_NETWORK=10.0.2.0/24 -e CEPH_DEMO_UID=qqq -e CEPH_DEMO_ACCESS_KEY=qqq -e CEPH_DEMO_SECRET_KEY=qqq --name rgw12 ceph/daemon:tag-stable-3.0-luminous-ubuntu-16.04 demo
creating /etc/ceph/ceph.client.admin.keyring
creating /etc/ceph/ceph.mon.keyring
creating /var/lib/ceph/bootstrap-osd/ceph.keyring
creating /var/lib/ceph/bootstrap-mds/ceph.keyring
creating /var/lib/ceph/bootstrap-rgw/ceph.keyring
creating /var/lib/ceph/bootstrap-rbd/ceph.keyring
monmaptool: monmap file /etc/ceph/monmap-ceph
monmaptool: set fsid to f16382be-092c-40b9-9069-0ada3f4dd657
monmaptool: writing epoch 0 to /etc/ceph/monmap-ceph (1 monitors)
importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-rgw/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /var/lib/ceph/bootstrap-rbd/ceph.keyring into /etc/ceph/ceph.mon.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /etc/ceph/ceph.mon.keyring
Error ENOENT: unrecognized pool 'rbd'
changed ownership of '/etc/ceph/ceph.client.admin.keyring' from root:root to ceph:ceph
changed ownership of '/etc/ceph/ceph.conf' from root:root to ceph:ceph
ownership of '/etc/ceph/ceph.mon.keyring' retained as ceph:ceph
changed ownership of '/var/lib/ceph/osd/ceph-0' from root:root to ceph:ceph
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup bluestore_block_size
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup bluestore_block_db_size
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup bluestore_block_size
command: Running command: /usr/bin/ceph-conf --cluster=ceph --name=osd. --lookup bluestore_block_wal_size
populate_data_path: Preparing osd data dir /var/lib/ceph/osd/ceph-0
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/ceph_fsid.195.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/fsid.195.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/magic.195.tmp
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/type.195.tmp
main_activate: path = /var/lib/ceph/osd/ceph-0
activate: Cluster uuid is f16382be-092c-40b9-9069-0ada3f4dd657
command: Running command: /usr/bin/ceph-osd --cluster=ceph --show-config-value=fsid
activate: Cluster name is ceph
activate: OSD uuid is a878c4b7-ae9b-41b8-964c-82cf5efadc90
allocate_osd_id: Allocating OSD id...
command: Running command: /usr/bin/ceph-authtool --gen-print-key
__init__: stderr 
command_with_stdin: Running command with stdin: ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new a878c4b7-ae9b-41b8-964c-82cf5efadc90
command_with_stdin: 0

command_check_call: Running command: /usr/bin/ceph-authtool /var/lib/ceph/osd/ceph-0/keyring --create-keyring --name osd.0 --add-key AQCxYORZszpAAxAAfFiyGHGhziz8aLGoEbzz1Q==
creating /var/lib/ceph/osd/ceph-0/keyring
added entity osd.0 auth auth(auid = 18446744073709551615 key=AQCxYORZszpAAxAAfFiyGHGhziz8aLGoEbzz1Q== with 0 caps)
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/keyring
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/whoami.214.tmp
activate: OSD id is 0
activate: Initializing OSD...
command_check_call: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-0/activate.monmap
got monmap epoch 1
command_check_call: Running command: /usr/bin/ceph-osd --cluster ceph --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --osd-data /var/lib/ceph/osd/ceph-0 --osd-uuid a878c4b7-ae9b-41b8-964c-82cf5efadc90 --setuser ceph --setgroup ceph
2017-10-16 07:33:05.622136 7f64eed40e00 -1 bdev(0x5558439c4900 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
2017-10-16 07:33:05.623374 7f64eed40e00 -1 bdev(0x5558439c4fc0 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
2017-10-16 07:33:06.153837 7f64eed40e00 -1 bdev(0x5558439c4900 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
2017-10-16 07:33:06.154902 7f64eed40e00 -1 bdev(0x5558439c4fc0 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
2017-10-16 07:33:06.694569 7f64eed40e00 -1 bdev(0x5558439c4900 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
2017-10-16 07:33:06.695485 7f64eed40e00 -1 bdev(0x5558439c4fc0 /var/lib/ceph/osd/ceph-0/block) unable to get device name for /var/lib/ceph/osd/ceph-0/block: (22) Invalid argument
2017-10-16 07:33:07.265759 7f64eed40e00 -1 created object store /var/lib/ceph/osd/ceph-0 for osd.0 fsid f16382be-092c-40b9-9069-0ada3f4dd657
command: Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/active.214.tmp
activate: ceph osd.0 data dir is ready at /var/lib/ceph/osd/ceph-0
ownership of '/var/lib/ceph/osd/ceph-0/magic' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/ready' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/active' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/ceph_fsid' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/bluefs' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/mkfs_done' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/fsid' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/block' retained as ceph:ceph
changed ownership of '/var/lib/ceph/osd/ceph-0/activate.monmap' from root:root to ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/type' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/whoami' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/keyring' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0/kv_backend' retained as ceph:ceph
ownership of '/var/lib/ceph/osd/ceph-0' retained as ceph:ceph
starting osd.0 at - osd_data /var/lib/ceph/osd/ceph-0 /var/lib/ceph/osd/ceph-0/journal
pool 'cephfs_data' created
pool 'cephfs_metadata' created
new fs with metadata pool 2 and data pool 1
changed ownership of '/var/lib/ceph/mds/ceph-0/keyring' from root:root to ceph:ceph
changed ownership of '/var/lib/ceph/mds/ceph-0' from root:root to ceph:ceph
2017-10-16 07:33:09.310099 7fcf9b343200 -1 deprecation warning: MDS id 'mds.0' is invalid and will be forbidden in a future version.  MDS names may not start with a numeric digit.
starting mds.0 at -
changed ownership of '/var/lib/ceph/radosgw/petertc-VirtualBox' from root:root to ceph:ceph
2017-10-16 07:33:09  /entrypoint.sh: Setting up a demo user...
```

**Comment by hrchu** [comment] 2017-10-24 00:36
Any update about this?

**Comment by leseb** [comment] 2019-01-18 14:47
I'm closing this since the issue is gone (based on comment https://github.com/ceph/ceph-container/issues/815#issuecomment-455440455). Thanks.

**Closed by leseb** 2019-01-18 14:47 UTC
